### ISSUE TITLE
Questions about mec_sample_dags()

### ISSUE THREAD

**Issue by kenneth-lee-ch** [mwien/CliquePicking#2]
Is the function `cp.mec_sample_dags` supposed to sample the same DAG more than once in Python? I found duplicate DAGs sampled by this function.

**Comment by kenneth-lee-ch** [comment]
Nevermind, I have read the reference paper and found that the sampling is uniform. Thank you.

**Comment by mwien** [comment]
No problem. I could add a function which returns a list of all DAGs in the MEC (each exactly once) provided that number is not prohibitively large if that helps you. Not sure if other python packages already support this...

**Comment by kenneth-lee-ch** [comment]
That would be perfect. I have been trying to implement a python version of your paper: Efficient Enumeration of Markov Equivalent DAGs..but I am not familiar with Julia and am stuck at the pseudocode of Algorithm 6 in that paper.

**Comment by mwien** [comment]
Do you have CPDAGs or MPDAGs? Just asking because Alg. 6 is about MPDAGs specifically (the case where you have additional background knowledge).

**Comment by kenneth-lee-ch** [comment]
I have a CPDAG and a PDAG that shouldn't be extended to a MPDAG with Meek rules.

**Comment by mwien** [comment]
Ok, I can add a first version of the enumeration code reasonably quickly. Will only be for CPDAGs and will for now return a list of DAGs or topological orders (use what you prefer). I'm working on this here: https://github.com/mwien/CliquePicking/pull/3

For now it will have the disadvantage that its really not usable if there is a large number of DAGs in the MEC or if the graphs get big because the memory needed to store all DAGs at once is too large. So could be it's not that helpful to you depending on your use case. 

Ultimately I want to provide an iterator in Python so you can write (and this is not an iterator over the list but the DAGs are produced one-by-one with memory usage independent of number of DAGs in the MEC):
```python
for dag in mec(g):
    # do stuff with dag
```

But this might take me a bit longer because it's not completely trivial to implement/interface with Python. 

I guess if you want to do something immediately (with the current functions) you could sample DAGs and discard repeated ones until you have all of them (the counting function gives you the size of the MEC). Not pretty, but if the number of DAGs is small will likely work (for $n$ DAGs in the class needs $n \cdot \log(n)$ draws in expectation).

**Comment by mwien** [comment]
@kenneth-lee-ch I added the functions ```mec_list_dags(G)``` and ```mec_list_orders(G)``` in the new version 0.2.4. Hope this helps you a bit!

I'm going to work on a version 0.3.0 with a better interface (returning an iterator instead of a list) in the next while. If you have any feedback or suggestions for this version, feel free to write.

Also I wrote the code relatively quickly, so I cannot rule out bugs. Maybe have some sanity checks in your code and please open an issue if something appears to be incorrect.

**Comment by kenneth-lee-ch** [comment]
@mwien Thank you so much! Currently, I am trying to sample a subset of unique DAGs from the MEC. Is there a way to avoid the computation expense in using the full version e.g. `mec_list_dags(G)` without using `mec_sample_dags` with a while loop for rejecting the same DAG?

**Comment by mwien** [comment]
Currently not. In the next major version, I will hopefully change/extend ```mec_list_dags(G)``` to just return an iterator so that you can take as many/few distinct graphs as you want. However, this will take a bit of time... (and would also not fix the "problem" in the next paragraph)

Now, I could provide a version ```mec_list_dags(G, k)``` which give $k$ unique DAGs from the class. But these would not be uniformly sampled (without repetition) but be extremely biased. This is because the listing procedure is very systematic (e.g. imagine you first list all DAGs which have all edges outgoing from vertex 1 and after all those with all edges outgoing from vertex 2 etc). Would this function still help you? 

If you instead need a randomly drawn subset, then there is no algorithm which immediately gives you $k$ unique graphs, but basically you could only do what you describe (using mec_sample_dags and filtering duplicate graphs). You could do this by having a ```set``` of graphs in python and this should work fine for smaller graphs/subsets. 

To avoid memory issues if you want a large subset for big graphs, I can imagine the following procedure:

- lets say you want $10^6$ distinct graphs, holding them all in memory at the same time might not be possible (in a ```set``` of graphs)
- instead have a ```set``` of integers, which stores the hash value of the already drawn graphs (there are many ways to get a hash of a graph), lets say we do it modulo $10^{50}$ or some other absurdly large number (as long as this doesn't exceed memory demand)
- then, we discard graphs for which we already saw the hash, else we use them and store the hash
- because the hash values are so large it is very very unlikely, we will discard a graph we have not seen before (have a "collision")

**Comment by kenneth-lee-ch** [comment]
@mwien  Wait, I missed your comment. I think the idea of an iterator will be super helpful. This is very crucial to a project that I am working on...

**Comment by mwien** [comment]
Probably will change the code at some point so one can do ```sampler = cp.Sampler(g)``` and afterwards ```sampler.sample()``` to sample DAGs.

But right now repeatedly calling ```cp.mec_sample_dags(g, 1)``` gives you the same functionality, it's just slower. Is performance the problem or what is the issue?

**Comment by kenneth-lee-ch** [comment]
If I repeatedly call on `cp.mec_sample_dags(g, 1)`, it won't give me unique DAGs. I just want to see if I can get k unique DAGs without sampling all the DAGs upfront.

**Comment by mwien** [comment]
Ok, so the sampling function no matter the API will never give unique DAGs. 

I still think you can handle that on your end even without storing every DAG you have already seen. E.g. by repeatedly calling ```cp.mec_sample_dags(g, 1)```, computing a hash for the sampled DAG and looking whether you've seen this hash before and rejecting the sample if you did. So you only store the hash values and repeatedly sample until you generate as many distinct graphs as you want.

For listing I'll probably provide an iterator but it's hard to promise anything because I'm not 100% sure it will work as currently planned. 

And as I wrote above: the graphs you get are not listed in a random but in a very systematic "sorted" order. So I don't think the listing iterator is useful for generating a random subset of DAGs in the MEC.

Still, it could be useful if one wants to go though all DAGs in the MEC but holding them in memory at once is too costly.

**Comment by mwien** [comment]
Just a quick info: I changed the sampling API to be class-based.  

From version 0.3 onwards, it works like this:
```
edges = [(0, 1), (1, 0)]
sampler = MecSampler(edges)
dag1 = sampler.sample_dag()
dag2 = sampler.sample_dag()
order = sampler.sample_order()
```
